export const ADD_PLAN_ITEM = 'ADD_PLAN_ITEM';
export const REMOVE_PLAN_ITEM = 'REMOVE_PLAN_ITEM';
export const COMPLETE_PLAN_ITEM = 'COMPLETE_PLAN_ITEM';
export const SUB_PLAN_QUANTITY = 'SUB_PLAN_QUANTITY';
export const ADD_PLAN_QUANTITY = 'ADD_PLAN_QUANTITY';
export const RESET = 'RESET';
